export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
export const SHOW_LOADER = 'SHOW_LOADER'
export const ADD_TODO = 'ADD_TODO'
export const FETCH_TODOS = 'FETCH_TODOS'
export const REMOVE_TODO = 'REMOVE_TODO'
